spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:50417/railway
spring.datasource.username=root
spring.datasource.password=wEizWEYCygPSI1SerjatmlJYGfqfdFZa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}